############################################################################################################################
## Regenerator, a Perpetual world plugin that integrates with Multiverse, Multiworld and several grief prevention plugins.##
############################################################################################################################

# The main configuration file no longer stores any data relating to what worlds to handle etc.
# For integration configuration, please see the /integrations/<plugin>.yml file associated with your grief protection plugin.
# For world configuration (Such as intervals between chunks), see /worlds/worldname/world.yml.

config-version: 2.0.0-Beta2

# This must be set to true if there are no grief prevention plugins installed and you want the plugin to work.
# WARNING: This means that the plugin will regnerate chunks that you may wish to remain protected!
no-grief-run: false
# Minimum TPS that the server must have to perform regeneration.
# This suspends regeneration and notifies anyone with the 'regenerator.notify' permission node when it disables/resumes.
min-tps-regen: 10.0
# This will cause a regeneration event on a chunk the server is unloading, if the right criteria are met.
# NOTE: This can cause lag because the server can often unload/load dozens of chunks at a time.
regen-on-chunk-unload: true
# This will cause a regeneration event on a chunk the server is loading, if the right criteria are met.
# NOTE: This can cause lag because the server can often unload/load dozens of chunks at a time.
regen-on-chunk-load: true
# This will cause a regeneration event on the chunk a player is leaving, if the criteria are met.
# NOTE: This can cause lag on larger servers with a lot of players, but it is optimised to only fire when a player changes chunk, cutting this down.
regen-on-player-change-chunk: true
# This will cause a regeneration event when a world is loaded. This will lag the server temporarily and notify all players with the regenerator.notify permission node.
regen-on-world-load: true
# This will cause a regeneration event when a world is unloaded. This will lag the server temporarily and notify all players with the regenerator.notify permission node.
regen-on-world-unload: true


