name: Regenerator
main: com.draksterau.Regenerator.Plugin
version: 1.1.0
depend: [Factions, MassiveCore]
commands:
   regenerator:
      description: Core Regenerator command.
      usage: /regenerator
