name: SRegen
main: com.stargatemc.SRegen.SRegen
version: 3.1.8
softdepend: [ Factions, GriefPrevention, WorldGuard, RedProtect, Landlord, Towny ]
description: SRegen is a perpetual world plugin that supports many grief prevention plugins.
author: Bysokar
website: https://www.spigotmc.org/resources/SRegen.23409/
commands:
   sregen:
      description: Core SRegen command.
      usage: /sregen
