name: Regenerator
main: com.draksterau.Regenerator.RegeneratorPlugin
version: 2.0.1
softdepend: [ Factions, GriefPrevention, WorldGuard, RedProtect ]
description: Regenerator is a perpetual world plugin that supports many grief prevention plugins.
author: Bysokar
website: https://www.spigotmc.org/resources/regenerator.21470/
commands:
   regenerator:
      description: Core Regenerator command.
      usage: /regenerator