name: Regenerator
main: com.draksterau.Regenerator.RegeneratorPlugin
version: 3.4.0
softdepend: [ WorldEdit, Factions, GriefPrevention, WorldGuard, RedProtect, Towny ]
description: Regenerator is a perpetual world plugin that supports many grief prevention plugins.
author: Bysokar
website: https://www.spigotmc.org/resources/regenerator.23409/
commands:
   regenerator:
      description: Core Regenerator command.
      usage: /regenerator
