name: Regenerator
main: com.draksterau.Regenerator.Plugin
version: 1.4.0
softdepend: [Factions, MassiveCore]
commands:
   regenerator:
      description: Core Regenerator command.
      usage: /regenerator
